### ISSUE TITLE
Support for multiple tags?

### ISSUE THREAD

**Issue by andmos** [redhat-actions/s2i-build#29]
### Question

Not sure if this is a bug or a feature request, so I'm doing it as a question 😄 

I want to use the `s2i-build` action, but we need to tag the image with multiple tags. So far as I can see, this action does not support it? 

My initial thought was to use the `push-to-registry` action to do all the tagging (since `push-to-registry` support a list of tags), but it looks like `push-to-registry` needs a 1 to 1 mapping between tags to push.

Anything I'm missing here, or does this go as a feature request to support multiple tags? 😄

**Comment by Divyansh42** [comment]
@andmos This seems to be a good feature request :+1: 
We will try to get this done :slightly_smiling_face:

**Comment by andmos** [comment]
From what I can see here, it might be that the tagging must be a separate tag step. Not sure if `s2i` support multiple tags without doing the tagging separately with e.g `docker tag`
https://github.com/redhat-actions/s2i-build/blob/4b558c78eab3a55e0316514cbcb5a2d853a76e1c/src/s2iExec.ts#L38

**Comment by andmos** [comment]
Here is an example of this done in Bash from a custom Action I've used:
```sh
set -e
if [ "$5" = "" ]; then
    echo "Skipping login for image pull - username not set."
else
    echo "Credentials for builder image registry detected - logging in."
#    echo "$6" | docker login "$4" --username "$5" --password-stdin
fi
# We will always need to login to the registry we intend to push to
#echo "$9" | docker login "$7" --username "$8" --password-stdin
# Grab builder image
docker pull "$2"
# Build
s2i build "$1" "$2" "$3"

TAGS="${10}"

if [ "$TAGS" = "" ]; then
    echo "Skipping custom tagging, using latest - tags not set."
else 
    for TAG in ${TAGS//,/ }
    do
        echo "Tagging image ${3} with ${TAG}"
        docker tag "${3}" "${3}:${TAG}"
    done
fi
# Push to output registry

docker push "$3"
```

**Comment by Divyansh42** [comment]
Yeah, we did same way in [buildah-build](https://github.com/redhat-actions/buildah-build) action.
There is no option to provide multiple tags in s2i.

**Comment by Divyansh42** [comment]
I am going to use `docker` here to tag, as s2i has dependency on `docker` 
Ref: https://github.com/openshift/source-to-image#dependencies

**Comment by Divyansh42** [comment]
Also added outputs `image` and `tags` which outputs name of image built and list of tags respectively. (similar to what we have in buildah-build action)

**Comment by Divyansh42** [comment]
@andmos you should be able to use this feature in `redhat-actions/s2i-build@v2`
