### ISSUE TITLE
GitHub Actions warning about deprecation of Node 12

### ISSUE THREAD

**Issue by WalterMoar** [redhat-actions/s2i-build#47]
### Version

redhat-actions/s2i-build@v2

### Describe the bug

Using the action produces the warning:

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: redhat-actions/s2i-build@v2

### Steps to reproduce, workflow links, screenshots

Run a workflow using s2i-build@v2, and afterwards the warning appears in the Annotations section below the flow diagram.

**Comment by divyansh42** [comment]
Latest action version `v2` and `v2.4` has been updated to node20
