### ISSUE TITLE
[BUG] latest S2I version is now v1.3.6

### ISSUE THREAD

**Issue by jmtd** [redhat-actions/s2i-build#51]
Various parts of this Action reference S2I v1.3.1 (and it's short hash a5a77147). The current latest versions of S2I is v1.3.6 (short hash cd7d7ce9). Please consider updating the action.

**Comment by divyansh42** [comment]
Latest version of s2i has been updated to v1.3.9

**Comment by divyansh42** [comment]
You can find the latest version in the release `v2` and `v2.4`
