### ISSUE TITLE
[FEATURE] document how to build from source

### ISSUE THREAD

**Issue by jmtd** [redhat-actions/s2i-build#52]
I wanted to fix a simple issue (#51). The strings to replace occur in these files
```
README.md
dist/index.js
dist/index.js.map
src/constants.ts
src/s2iExec.ts
```
I'm fairly sure the contents of `dist` are generated by a build process but I don't know what it is. Please consider adding a `HACKING` file or similar documenting what tools to use to produce this. Thanks!

**Comment by divyansh42** [comment]
Latest version of s2i has been updated to `v1.3.9`

**Comment by divyansh42** [comment]
You can find the latest version in the release `v2` and `v2.4`
